main:
  - name: Forside
    url: /
    weight: 10
  - name: Om mig
    url: /om-mig/
    weight: 20
  - name: Akademisk arbejde
    url: /akademisk-arbejde/
    weight: 30
  - name: Undervisningsmateriale
    url: /undervisningsmateriale/
    weight: 40
  - name: Foredrag & formidling
    url: /foredrag-formidling/
    weight: 50
  - name: Andet
    identifier: andet
    weight: 60
  - name: Tankemylder
    url: /tankemylder/
    parent: andet
    weight: 10
  - name: Birds With Apps
    url: /birds-with-apps/
    parent: andet
    weight: 20
  - name: CV
    url: /cv/
    parent: andet
    weight: 30
  - name: Kontakt
    url: /kontakt/
    parent: andet
    weight: 40
